# 01 - Data Fetching
Fetch 2023 F1 race results using FastF1 and save to the `/data` folder.

In [3]:
import fastf1
import pandas as pd
import os

In [4]:
# Create cache folder if it doesn't exist
os.makedirs('../data/cache', exist_ok=True)

# Tell FastF1 to use it
fastf1.Cache.enable_cache('../data/cache')

In [5]:
session = fastf1.get_session(2023,'bahrain','R')
session.load()

core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.2]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '55', '44', '18', '63', '77', '10', '23', '22', '2', '20', '21', '27', '24', '4', '31', '16', '81']

In [7]:
results = session.results
print(results.shape)
results.head(20)

(20, 22)

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
1,1,M VERSTAPPEN,VER,max_verstappen,Red Bull Racing,3671C6,red_bull,Max,Verstappen,Max Verstappen,...,1.0,1,1.0,NaT,NaT,NaT,0 days 01:33:56.736000,Finished,25.0,57.0
11,11,S PEREZ,PER,perez,Red Bull Racing,3671C6,red_bull,Sergio,Perez,Sergio Perez,...,2.0,2,2.0,NaT,NaT,NaT,0 days 00:00:11.987000,Finished,18.0,57.0
14,14,F ALONSO,ALO,alonso,Aston Martin,358C75,aston_martin,Fernando,Alonso,Fernando Alonso,...,3.0,3,5.0,NaT,NaT,NaT,0 days 00:00:38.637000,Finished,15.0,57.0
55,55,C SAINZ,SAI,sainz,Ferrari,F91536,ferrari,Carlos,Sainz,Carlos Sainz,...,4.0,4,4.0,NaT,NaT,NaT,0 days 00:00:48.052000,Finished,12.0,57.0
44,44,L HAMILTON,HAM,hamilton,Mercedes,6CD3BF,mercedes,Lewis,Hamilton,Lewis Hamilton,...,5.0,5,7.0,NaT,NaT,NaT,0 days 00:00:50.977000,Finished,10.0,57.0
18,18,L STROLL,STR,stroll,Aston Martin,358C75,aston_martin,Lance,Stroll,Lance Stroll,...,6.0,6,8.0,NaT,NaT,NaT,0 days 00:00:54.502000,Finished,8.0,57.0
63,63,G RUSSELL,RUS,russell,Mercedes,6CD3BF,mercedes,George,Russell,George Russell,...,7.0,7,6.0,NaT,NaT,NaT,0 days 00:00:55.873000,Finished,6.0,57.0
77,77,V BOTTAS,BOT,bottas,Alfa Romeo,C92D4B,alfa,Valtteri,Bottas,Valtteri Bottas,...,8.0,8,12.0,NaT,NaT,NaT,0 days 00:01:12.647000,Finished,4.0,57.0
10,10,P GASLY,GAS,gasly,Alpine,2293D1,alpine,Pierre,Gasly,Pierre Gasly,...,9.0,9,20.0,NaT,NaT,NaT,0 days 00:01:13.753000,Finished,2.0,57.0
23,23,A ALBON,ALB,albon,Williams,37BEDD,williams,Alexander,Albon,Alexander Albon,...,10.0,10,15.0,NaT,NaT,NaT,0 days 00:01:29.774000,Finished,1.0,57.0
22,22,Y TSUNODA,TSU,tsunoda,AlphaTauri,5E8FAA,alphatauri,Yuki,Tsunoda,Yuki Tsunoda,...,11.0,11,14.0,NaT,NaT,NaT,0 days 00:01:30.870000,Finished,0.0,57.0
2,2,L SARGEANT,SAR,sargeant,Williams,37BEDD,williams,Logan,Sargeant,Logan Sargeant,...,12.0,12,16.0,NaT,NaT,NaT,0 days 00:00:01.136000,Lapped,0.0,56.0
20,20,K MAGNUSSEN,MAG,kevin_magnussen,Haas F1 Team,B6BABD,haas,Kevin,Magnussen,Kevin Magnussen,...,13.0,13,17.0,NaT,NaT,NaT,0 days 00:00:16.757000,Lapped,0.0,56.0
21,21,N DE VRIES,DEV,de_vries,AlphaTauri,5E8FAA,alphatauri,Nyck,De Vries,Nyck De Vries,...,14.0,14,19.0,NaT,NaT,NaT,0 days 00:00:22.523000,Lapped,0.0,56.0
27,27,N HULKENBERG,HUL,hulkenberg,Haas F1 Team,B6BABD,haas,Nico,Hulkenberg,Nico Hulkenberg,...,15.0,15,10.0,NaT,NaT,NaT,0 days 00:00:38.911000,Lapped,0.0,56.0
24,24,G ZHOU,ZHO,zhou,Alfa Romeo,C92D4B,alfa,Guanyu,Zhou,Guanyu Zhou,...,16.0,16,13.0,NaT,NaT,NaT,0 days 00:00:39.649000,Lapped,0.0,56.0
4,4,L NORRIS,NOR,norris,McLaren,F58020,mclaren,Lando,Norris,Lando Norris,...,17.0,17,11.0,NaT,NaT,NaT,0 days 00:00:06.636000,Lapped,0.0,55.0
31,31,E OCON,OCO,ocon,Alpine,2293D1,alpine,Esteban,Ocon,Esteban Ocon,...,18.0,R,9.0,NaT,NaT,NaT,NaT,Retired,0.0,41.0
16,16,C LECLERC,LEC,leclerc,Ferrari,F91536,ferrari,Charles,Leclerc,Charles Leclerc,...,19.0,R,3.0,NaT,NaT,NaT,NaT,Retired,0.0,39.0
81,81,O PIASTRI,PIA,piastri,McLaren,F58020,mclaren,Oscar,Piastri,Oscar Piastri,...,20.0,R,18.0,NaT,NaT,NaT,NaT,Retired,0.0,13.0

In [9]:
columns_to_keep = [
    'DriverNumber', 'BroadcastName', 'FullName',
    'TeamName', 'Position', 'Points', 'Status',
    'GridPosition', 'Time'
]
df = results[columns_to_keep].copy()
df.head(20)

,DriverNumber,BroadcastName,FullName,TeamName,Position,Points,Status,GridPosition,Time
1,1,M VERSTAPPEN,Max Verstappen,Red Bull Racing,1.0,25.0,Finished,1.0,0 days 01:33:56.736000
11,11,S PEREZ,Sergio Perez,Red Bull Racing,2.0,18.0,Finished,2.0,0 days 00:00:11.987000
14,14,F ALONSO,Fernando Alonso,Aston Martin,3.0,15.0,Finished,5.0,0 days 00:00:38.637000
55,55,C SAINZ,Carlos Sainz,Ferrari,4.0,12.0,Finished,4.0,0 days 00:00:48.052000
44,44,L HAMILTON,Lewis Hamilton,Mercedes,5.0,10.0,Finished,7.0,0 days 00:00:50.977000
18,18,L STROLL,Lance Stroll,Aston Martin,6.0,8.0,Finished,8.0,0 days 00:00:54.502000
63,63,G RUSSELL,George Russell,Mercedes,7.0,6.0,Finished,6.0,0 days 00:00:55.873000
77,77,V BOTTAS,Valtteri Bottas,Alfa Romeo,8.0,4.0,Finished,12.0,0 days 00:01:12.647000
10,10,P GASLY,Pierre Gasly,Alpine,9.0,2.0,Finished,20.0,0 days 00:01:13.753000
23,23,A ALBON,Alexander Albon,Williams,10.0,1.0,Finished,15.0,0 days 00:01:29.774000
22,22,Y TSUNODA,Yuki Tsunoda,AlphaTauri,11.0,0.0,Finished,14.0,0 days 00:01:30.870000
2,2,L SARGEANT,Logan Sargeant,Williams,12.0,0.0,Lapped,16.0,0 days 00:00:01.136000
20,20,K MAGNUSSEN,Kevin Magnussen,Haas F1 Team,13.0,0.0,Lapped,17.0,0 days 00:00:16.757000
21,21,N DE VRIES,Nyck De Vries,AlphaTauri,14.0,0.0,Lapped,19.0,0 days 00:00:22.523000
27,27,N HULKENBERG,Nico Hulkenberg,Haas F1 Team,15.0,0.0,Lapped,10.0,0 days 00:00:38.911000
24,24,G ZHOU,Guanyu Zhou,Alfa Romeo,16.0,0.0,Lapped,13.0,0 days 00:00:39.649000
4,4,L NORRIS,Lando Norris,McLaren,17.0,0.0,Lapped,11.0,0 days 00:00:06.636000
31,31,E OCON,Esteban Ocon,Alpine,18.0,0.0,Retired,9.0,NaT
16,16,C LECLERC,Charles Leclerc,Ferrari,19.0,0.0,Retired,3.0,NaT
81,81,O PIASTRI,Oscar Piastri,McLaren,20.0,0.0,Retired,18.0,NaT

In [10]:
df['year'] = 2023
df['RaceName']= 'Bahrain'
df['Round']= 1

df.head(20)

,DriverNumber,BroadcastName,FullName,TeamName,Position,Points,Status,GridPosition,Time,year,RaceName,Round
1,1,M VERSTAPPEN,Max Verstappen,Red Bull Racing,1.0,25.0,Finished,1.0,0 days 01:33:56.736000,2023,Bahrain,1
11,11,S PEREZ,Sergio Perez,Red Bull Racing,2.0,18.0,Finished,2.0,0 days 00:00:11.987000,2023,Bahrain,1
14,14,F ALONSO,Fernando Alonso,Aston Martin,3.0,15.0,Finished,5.0,0 days 00:00:38.637000,2023,Bahrain,1
55,55,C SAINZ,Carlos Sainz,Ferrari,4.0,12.0,Finished,4.0,0 days 00:00:48.052000,2023,Bahrain,1
44,44,L HAMILTON,Lewis Hamilton,Mercedes,5.0,10.0,Finished,7.0,0 days 00:00:50.977000,2023,Bahrain,1
18,18,L STROLL,Lance Stroll,Aston Martin,6.0,8.0,Finished,8.0,0 days 00:00:54.502000,2023,Bahrain,1
63,63,G RUSSELL,George Russell,Mercedes,7.0,6.0,Finished,6.0,0 days 00:00:55.873000,2023,Bahrain,1
77,77,V BOTTAS,Valtteri Bottas,Alfa Romeo,8.0,4.0,Finished,12.0,0 days 00:01:12.647000,2023,Bahrain,1
10,10,P GASLY,Pierre Gasly,Alpine,9.0,2.0,Finished,20.0,0 days 00:01:13.753000,2023,Bahrain,1
23,23,A ALBON,Alexander Albon,Williams,10.0,1.0,Finished,15.0,0 days 00:01:29.774000,2023,Bahrain,1
22,22,Y TSUNODA,Yuki Tsunoda,AlphaTauri,11.0,0.0,Finished,14.0,0 days 00:01:30.870000,2023,Bahrain,1
2,2,L SARGEANT,Logan Sargeant,Williams,12.0,0.0,Lapped,16.0,0 days 00:00:01.136000,2023,Bahrain,1
20,20,K MAGNUSSEN,Kevin Magnussen,Haas F1 Team,13.0,0.0,Lapped,17.0,0 days 00:00:16.757000,2023,Bahrain,1
21,21,N DE VRIES,Nyck De Vries,AlphaTauri,14.0,0.0,Lapped,19.0,0 days 00:00:22.523000,2023,Bahrain,1
27,27,N HULKENBERG,Nico Hulkenberg,Haas F1 Team,15.0,0.0,Lapped,10.0,0 days 00:00:38.911000,2023,Bahrain,1
24,24,G ZHOU,Guanyu Zhou,Alfa Romeo,16.0,0.0,Lapped,13.0,0 days 00:00:39.649000,2023,Bahrain,1
4,4,L NORRIS,Lando Norris,McLaren,17.0,0.0,Lapped,11.0,0 days 00:00:06.636000,2023,Bahrain,1
31,31,E OCON,Esteban Ocon,Alpine,18.0,0.0,Retired,9.0,NaT,2023,Bahrain,1
16,16,C LECLERC,Charles Leclerc,Ferrari,19.0,0.0,Retired,3.0,NaT,2023,Bahrain,1
81,81,O PIASTRI,Oscar Piastri,McLaren,20.0,0.0,Retired,18.0,NaT,2023,Bahrain,1

In [11]:
df['Top3'] = (df['Position'] <= 3).astype(int)

print(df[['FullName', 'Position', 'Top3']])

           FullName  Position  Top3
1    Max Verstappen       1.0     1
11     Sergio Perez       2.0     1
14  Fernando Alonso       3.0     1
55     Carlos Sainz       4.0     0
44   Lewis Hamilton       5.0     0
18     Lance Stroll       6.0     0
63   George Russell       7.0     0
77  Valtteri Bottas       8.0     0
10     Pierre Gasly       9.0     0
23  Alexander Albon      10.0     0
22     Yuki Tsunoda      11.0     0
2    Logan Sargeant      12.0     0
20  Kevin Magnussen      13.0     0
21    Nyck De Vries      14.0     0
27  Nico Hulkenberg      15.0     0
24      Guanyu Zhou      16.0     0
4      Lando Norris      17.0     0
31     Esteban Ocon      18.0     0
16  Charles Leclerc      19.0     0
81    Oscar Piastri      20.0     0

In [14]:
os.makedirs('../data', exist_ok=True)

df.to_csv('../data/bahrain_2023.csv', index=False)

print("Saved! ✅")

Saved! ✅

 # Fetch multiple races in a loop